id = "zed-netlinx"
name = "NetLinx"
version = "0.1.0"
schema_version = 1
authors = ["22627489+damienbutt@users.noreply.github.com"]
description = "Syntax highlighting for the NetLinx programming language"
repository = "https://github.com/Norgate-AV/zed-netlinx"
snippets = "./snippets/netlinx.json"

[grammars.netlinx]
repository = "https://github.com/Norgate-AV/tree-sitter-netlinx"
rev = "5639014332c4aa1d930e58a052c0a34cf99a4526"
