id = "netlinx"
name = "NetLinx"
version = "0.1.0"
schema_version = 1
authors = ["Damien Butt <22627489+damienbutt@users.noreply.github.com>"]
description = "NetLinx support for Zed"
repository = "https://github.com/Norgate-AV/zed-netlinx"
snippets = "./snippets/netlinx.json"

[grammars.netlinx]
repository = "https://github.com/Norgate-AV/tree-sitter-netlinx"
rev = "296c0e62cd507fc23cd1f1db06142f808483cf1a"
