name = "NetLinx"
grammar = "netlinx"
path_suffixes = ["axs", "axi", "axb", "lib"]
line_comments = ["// "]
block_comment = { start = "/*", end = "*/", prefix = "* ", tab_size = 1 }
documentation_comment = { start = "/**", prefix = "* ", end = "*/", tab_size = 1 }
tab_size = 4
hard_tabs = false
first_line_pattern = "(?i)^(program|module)_name\\s*=.*$"
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "/*", end = " */", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "(*", end = " *)", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
import_path_strip_regex = "^'|'$"
